export const helpers = {
  experienceHeading: "FOLLOW WHAT MOVES YOU",
  skip: "Skip to content",
  navLabel: "Main navigation",
  language: "English — additional languages can be added",
  scroll: "Scroll to discover",
  scrollText: "SCROLL TO DISCOVER",
  editorial: "A world closer\nthan you think.",
  ribbon: [
    "Curated with local perspective",
    "Made personal, from the very beginning",
    "No fixed packages. Just possibilities.",
  ],
  photos:
    "Atmospheric imagery for the design preview. Destination photography will be curated before launch.",
  slower: "A slower moment. A deeper connection.",
  firstChapter: "Our first chapter",
  horizon: "MORE STORIES ON THE HORIZON",
  unavailable: "no requests available yet",
  wonder: "Leave room for wonder.",
  messageDemo: "Design preview: your message is not sent or stored.",
  messagePlaceholder: "A slower week in the mountains, a little culture…",
  previewLabel: "Design preview",
  dateDescription: "A fixed plan or a little flexibility — both are welcome.",
  datesError:
    "Choose your arrival and departure dates, or select flexible dates.",
  orderError: "Departure must be on or after arrival.",
  adultsAge: "Ages 12 and above",
  childrenAge: "Under 12",
  durationHint: "About 3 minutes. Entirely yours.",
  fallbackPlan: [
    "Arrival and time to settle in Baku",
    "Discover your interests with a local guide",
    "A day shaped around your preferred experiences",
  ],
  day: "DAY",
  pace: "Time to explore, at your own pace.",
  stay: "Stay",
  transport: "Transport",
  experiences: "Experiences",
  noBooking: "No prices or bookings are confirmed at this stage.",
  detailsDemo:
    "Design preview: your details are not sent or stored. No online payment or instant confirmation.",
  summaryTitle: "A little adventure,\na lot of possibility.",
  travellers: "Travellers",
  adultUnit: "adults",
  childUnit: "children",
  summaryNote:
    "A starting point, not a booking.\nWe’ll shape the final journey together.",
  window: "Your travel window is",
  stops:
    "illustrative stops are not a complete day-by-day schedule. Our team will arrange your chosen places across your travel dates.",
  previewContact: "Contact details",
  previewTrip: "Your travel preferences",
  edit: "Edit my request",
  steps: [
    "01 / THE ESSENTIALS",
    "02 / YOUR INTERESTS",
    "03 / PLACES & STAYS",
    "04 / YOUR JOURNEY",
    "05 / YOUR DETAILS",
  ],
};
