export const refinement = {
  heroLocation: "THE ROAD TO DISCOVERY · AZERBAIJAN",
  heroCaption: "The highlands are only the beginning.",
  heroEdition: "OUR FIRST CHAPTER / AZERBAIJAN",
  exploreTours: "Explore tours",
  build: "Build your trip",
  customize: "Customize this trip",
  request: "Request this journey",
  add: "Add to my trip",
  start: "Start from this itinerary",
  send: "Send my request",
  view: "View journey",
  featured: "A FEW JOURNEYS, CHOSEN WITH CARE",
  featuredTitle: "A starting point.\nA story of your own.",
  featuredText:
    "Real routes. Beautiful possibilities. Every journey can be personalised.",
  signature: "THE SIGNATURE JOURNEY",
  experienceLabel: "FOLLOW WHAT MOVES YOU",
  experienceTitle: "Less ticking boxes.\nMore feeling something.",
  experienceText:
    "Choose a feeling, find an experience. We’ll make the connections.",
  allExperiences: "Explore experiences",
  momentLabel: "A LITTLE CLOSER TO THE EVERYDAY",
  momentTitle: "Some of the best discoveries\naren’t on a map.",
  momentText:
    "A courtyard in Sheki. A shared table in a mountain village. Give yourself time to find the moments between the highlights.",
  momentCaption: "A MOMENT OF HOSPITALITY / AZERBAIJAN",
  momentLink: "Discover Sheki",
  localLabel: "PERSONAL BY NATURE",
  localTitle: "Thoughtful planning.\nPeople you can talk to.",
  localText:
    "From your first idea to the final proposal, our approach is personal: considered routes, local perspective and a conversation about what matters to you.",
  trustCards: [
    {
      title: "Local perspective",
      text: "Explore places through their stories, people and everyday details.",
    },
    {
      title: "A journey that fits",
      text: "Choose your interests, stays and pace. We’ll shape a proposal around them.",
    },
    {
      title: "A real conversation",
      text: "No instant confirmations. Your request is reviewed by our team.",
    },
  ],
  itinerary: "Your journey, day by day",
  itineraryText:
    "Feel the rhythm of each day. Open the itinerary details when you want a closer look at the route.",
  dayDetails: "See itinerary details",
  hideDayDetails: "Hide itinerary details",
  highlights: "The moments to look forward to",
  overnight: "Overnight",
  gallery: "A few glimpses of the journey",
  stay: "A place to come back to",
  practical: "Good to know",
  duration: "Duration",
  nights: "nights",
  route: "The route",
  style: "Travel style",
  noPayment:
    "A personal proposal, prepared by our team. No online payment or automatic booking confirmation.",
  destinationWhy: "Why go",
  places: "A little closer",
  suggested: "Journeys through here",
  suited: "Follow your interests",
  related: "More ways to discover",
  photos: "An independent B2C visual story · AI-created editorial scenes",
  countryNext: "More destinations, thoughtfully added in the next chapters.",
  experiencesPage: {
    label: "CHOOSE THE WAY YOU WANT TO FEEL",
    title: "Follow a feeling.\nFind your journey.",
    text: "A quiet trail. A table shared with locals. A city with a different story. Choose what moves you, then add it to your journey.",
  },
  builder: {
    step: "Step",
    of: "of",
    edit: "Edit",
    summary: "View my journey",
    closeSummary: "Close journey summary",
    selected: "selected",
    nothing: "Open to suggestions",
    saved: "Your choices stay with you as you explore.",
    tourStart: "Starting from",
    customPlan: "Your personal journey",
    progress: "Journey progress",
    review: "Review your journey",
    reviewText:
      "Check your starting itinerary and preferences. Revisit any completed step without losing your choices.",
    base: "Starting itinerary",
    adjustments: "Requested route changes",
    adjustmentText:
      "You’ve changed the places in this route. The plan below is the original starting point; our team will adapt it in your proposal.",
    added: "Added places",
    removed: "Places to leave out",
    sourceDays: "days in the starting itinerary",
    dateMismatch:
      "Your dates differ from the starting itinerary. Our team will adjust the pace and route in your proposal.",
    chooseDates:
      "Choose both dates, or clear both fields and keep your dates flexible.",
    pastDate: "Choose today or a future arrival date.",
    phoneError: "Enter a phone or WhatsApp number with at least 7 digits.",
    nameError: "Please enter your first name, last name and country.",
    ready: "Your request preview is ready.",
    readyText:
      "Your journey is taking shape. This is a demo confirmation: no details have been sent or saved, and no booking has been made.",
    next: "What happens next",
    nextSteps: [
      {
        title: "A thoughtful review",
        text: "When connected, your request reaches the team for a personal review.",
      },
      {
        title: "A proposal made for you",
        text: "The team prepares your route, accommodation options and quotation.",
      },
      {
        title: "A conversation, then a decision",
        text: "You discuss the details before any arrangements are confirmed.",
      },
    ],
    demo: "Demo mode · Your details are not sent or stored.",
    missing: "Still to choose",
    preview: "Request preview",
    clearTour: "Plan freely",
    dateFlexible: "Dates flexible around these preferences",
    chooseCountry: "Country of travel",
    preferences: "Your preferences",
    included: "Included in your request",
    submittedItinerary: "Starting day-by-day itinerary",
    flexibleRoute:
      "Illustrative stops — our team will shape the final order and duration.",
    selectionFeedback: "Your preferences have been updated.",
  },
};
